name: Build and push the PI Operations container image

on:
  push:
    branches:
      - main
    paths:
      - 'WSEIdentify/pi-operations/**'
      - '.github/workflows/pi.container.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

concurrency:
  group: "PI Container"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          sparse-checkout: "WSEIdentify/pi-operations"
          sparse-checkout-cone-mode: false

      - name: Move files in the "pi-operations" folder to the root
        run: |
          ls -lah
          shopt -s dotglob
          mv WSEIdentify/pi-operations/* .
          rm -rf WSEIdentify/pi-operations
          ls -lah

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Build the docker image
        run: |
          docker buildx build . --tag ghcr.io/${{ env.REPO }}-pi-operations:latest
          docker push ghcr.io/${{ env.REPO }}-pi-operations:latest