name: Build and push the Web container image

on:
  push:
    branches:
      - main
    paths:
      - 'WSEIdentify/web/**'
      - '.github/workflows/web.container.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

concurrency:
  group: "Web Container"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          sparse-checkout: "WSEIdentify/web"
          sparse-checkout-cone-mode: false

      - name: Move files in the "web" folder to the root
        run: |
          ls -lah
          shopt -s dotglob
          mv WSEIdentify/web/* .
          rm -rf WSEIdentify/web
          ls -lah

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: downcase REPO
        run: |
          echo "REPO=${github.repository,,}" >>${GITHUB_ENV}
      - name: Build the docker image
        run: |
          docker build . --tag ghcr.io/${{ env.GITHUB_ENV }}-web:latest
          docker push ghcr.io/${{ env.GITHUB_ENV }}-web:latest